// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfeovzjcgbffrrvxfpjx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmZW92empjZ2JmZnJydnhmcGp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwODQwODYsImV4cCI6MjA2NDY2MDA4Nn0.kmK8d0BfiZCU1s2J6gmsE5uXqpSq1b67SRtNyaJpwMk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);